name: Test yafowil

on:
  push:
    branches:
      - 3.0
  workflow_dispatch:
    branches:
      - 3.0

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python:
          - "2.7"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install
        run: |
          pip install coverage
          pip install https://github.com/conestack/plumber/archive/master.zip
          pip install https://github.com/conestack/node/archive/master.zip
          pip install -e .[test]

      - name: Run tests
        run: |
          python --version
          python -m yafowil.tests.__init__

      - name: Run coverage
        run: |
          coverage run --source=src/yafowil -m yafowil.tests.__init__
          coverage report -m --fail-under=99
